export const USER_API_END_POINT = "http://localhost:8000/api/users"
export const APARTMENT_API_END_POINT = "http://localhost:8000/api/apartments"
export const AGREEMENT_API_END_POINT = "http://localhost:8000/api/agreements"
export const ANNOUNCEMENT_API_END_POINT = "http://localhost:8000/api/announcements"
export const PAYMENT_API_END_POINT = "http://localhost:8000/api/payments"
export const CUPONS_API_END_POINT = "http://localhost:8000/api/coupons"