export const USER_API_END_POINT = "https://flatflow.vercel.app/api/users"
export const APARTMENT_API_END_POINT = "https://flatflow.vercel.app/api/apartments"
export const AGREEMENT_API_END_POINT = "https://flatflow.vercel.app/api/agreements"
export const ANNOUNCEMENT_API_END_POINT = "https://flatflow.vercel.app/api/announcements"
export const PAYMENT_API_END_POINT = "https://flatflow.vercel.app/api/payments"
export const CUPONS_API_END_POINT = "https://flatflow.vercel.app/api/coupons"